import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  // index("routes/home.tsx"),
  index("./routes/book.tsx"),
  route("/login", "./routes/login.tsx"),
  route("/book/ride", "./routes/ride.tsx"),
  route("/ride-details", "./routes/ride-details.tsx"),
  route("/profile", "./routes/profile.tsx"),
  route("/profile-details", "./routes/profile-details.tsx"),
  route("/chat", "./routes/chat.tsx"),
  route("/reviews", "./routes/reviews.tsx"),
  route("/payment", "./routes/payment.tsx"),
  route("/publish", "./routes/publish.tsx"),
  route("/pickup", "./routes/pickup.tsx"),
  route("/dropoff", "./routes/dropoff.tsx"),
  route("/route", "./routes/route.tsx"),
  route("/stopovers", "./routes/stopovers.tsx"),
  route("/stopovers-preview", "./routes/stopovers-preview.tsx"),
  route("/date", "./routes/date.tsx"),
  route("/time", "./routes/time.tsx"),
  route("/passenger-count", "./routes/passenger-count.tsx"),
  route("/pricing", "./routes/pricing.tsx"),
  route("/return", "./routes/return.tsx"),
  route("/publish-comment", "./routes/publish-comment.tsx"),
  route("/publish-ride", "./routes/publish-ride.tsx"),
  route("/your-ride", "./routes/your-ride.tsx"),
  route("/your-publication", "./routes/your-publication.tsx"),
  route("/itinerary", "./routes/itinerary.tsx"),
  route("/passenger-options", "./routes/passenger-options.tsx"),
  route("/your-pricing", "./routes/your-pricing.tsx"),
  route("/passenger-profile", "./routes/passenger-profile.tsx"),
  route("/your-rides", "./routes/your-rides.tsx"),
  route("/add-vehicles", "./routes/add-vehicles.tsx"),
  route("/vehicle-category", "./routes/vehicle-category.tsx"),
  route("/vehicle-model", "./routes/vehicle-model.tsx"),
  route("/vehicle-color", "./routes/vehicle-color.tsx"),
  route("/booking-request", "./routes/booking-request.tsx"),
  route("/booking-request-details", "./routes/booking-request-details.tsx"),
  route("/user-profile", "./routes/user-profile.tsx"),
  route("/change-password", "./routes/change-password.tsx"),
  route("/inbox", "./routes/inbox.tsx"),
  route("/transactions", "./routes/transaction-list.tsx"),
  route("/payment-refunds", "./routes/payment-refunds.tsx"),
  route("/bank-details", "./routes/bank-details.tsx"),
] satisfies RouteConfig;
